# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)










u1 = User.create(name:"nick", password:"password", dateofbirth:Date.parse('1991-08-21'), email:"email@email.com", avatar_url:"https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fcruiseweb.com%2Fblog%2Fwp-content%2Fuploads%2F2014%2F01%2Fwinelovers.jpg&f=1&nofb=1", city:"city", state:"state", address:"address", zipcode:12345)
u2 = User.create(name:"rick", password:"password", dateofbirth:Date.parse('2001-08-21'), email:"email@email.com", avatar_url:"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.todayifoundout.com%2Fwp-content%2Fuploads%2F2018%2F05%2Fwine-snob-640x445.png&f=1&nofb=1", city:"city", state:"state", address:"address", zipcode:12345)


#wines

Wine.create!(title: "Screaming Eagle", year: 2014, varietal: "Cabernet Sauvignon", description: "Extremely perfumed with blackberries, currants and flower. Rose petals, too. Seductive. Medium to full body. It grows on the palate with an extremely long finish that goes on for minutes. The tannins are ultra-fine and polished. Purity and essence to this. Feminine yet wild and unpredictable. Available in March. Better in 2021.", score: 95, price: 3000, country: "USA", region: "Napa Valley, CA", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/gd9tzt32lboid0xvstiu.jpg", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/165265.jpg")

Wine.create!(title: "Carlisle Papera Ranch", year: 2017, varietal: "Zinfandel", description: "The 2017 Zinfandel Papera Ranch comes from a site close to the Mancini Ranch and vines planted in 1934. Notes of plums, blueberries, violets, and earthy, herbal notes all flow to a full-bodied, incredibly deep, layered and concentrated 2017 that certainly makes the most of the vintage. With ripe tannins, remarkable purity of fruit, no hard edges, and flawless balance, it’s another gem in the vintage.", score: 94, price: 52, country: "USA", region: "Russian River, CA", second_img_url:"https://www.wine.com/product/images/w_768,h_2304,c_fit,q_auto:good,fl_progressive/nqshal8xse046v5g2vmh.jpg
", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/jrfynqsxbtozhgyxcf9f.jpg")

# https://www.wine.com/product/images/w_768,h_1641,c_fit,q_auto:good,fl_progressive/111778fbs.jpg


w1 = Wine.create!(title: "Chateau Lafite Rothschild", year: 2009, varietal: "Bordeaux", second_img_url:"https://www.wine.com/product/images/w_768,h_1641,c_fit,q_auto:good,fl_progressive/111778fbs.jpg", description: "This is stunning for its ability to take massively endowed fig, currant paste and crushed plum fruit flavors and harness them with ultrasuave freshly roasted espresso, black tea and ganache notes. A seductive style, long and velvety, with the dense core of black fruit and smoldering iron just waiting and waiting. Best from 2020 through 2040.", score: 98, price: 1250, country: "France", region: "Pauillac, Bordeaux", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/111778.jpg")

Wine.create!(title: "Nobilo", year: 2018, varietal: "Sauvignon Blanc", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/vum5oz6efvpl587donkg.jpg", description: "Fresh, crisp and clean with zesty flavors of ripe tropical fruits, especially passionfruit and pineapple with subtle hints of green herbs. The wine is intensely flavored with balanced mouthwatering acidity and a generous finish.", score: 89, price: 12, country: "New Zealand ", region: "Marlborough", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/dfhr3cjnfn6u7elqk75j.jpg")

Wine.create!(title: "Olivier Leflaive", year: 2017, varietal: "Chardonnay", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/kxgvv1n8nfabwyz5ohpj.jpg", description: "Fermented and aged in wood, this is a rich wine. Its spice, ripe pineapple and mango flavors and dense texture show intense freshness as well as layers of toast, a complex texture and a short aging potential. Drink from 2021.", score: 82, price: 90, country: "France", region: "Puligny-Montrachet, Cote de Beaune, Cote d'Or, Burgundy, France", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/wo6adueiwjczv2wu3qf3.jpg")

Wine.create!(title: "Nino Franco Rustico Prosecco Superiore", year: 2016, varietal: "Sparkling Wine", second_img_url:"https://www.wine.com/product/images/w_768,h_2822,c_fit,q_auto:good,fl_progressive/hn6yhk9ozhd9cocgyiuf.jpg", description: "Aromas of white spring flower, Bartlett pear and citrus waft out of the glass. The racy, refreshing palate is full of energy, offering crisp yellow-apple, lemon drop and orange zest flavors balanced by vibrant acidity. A perlage of small, refined and continuous bubbles provides the silky backdrop.", score: 94, price: 20, country: "Italy", region: "Valdobbiadene, Prosecco", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/vffikxhgjrsuciyefctp.jpg")

Wine.create!(title: "Chateau Petrus", year: 2016, varietal: "Bordeaux", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/pr86drcliihcoficfldf.jpg", description: "This is very fleshy and deep with so much texture and richness. It’s full-bodied yet fresh. The tobacco, white truffle, licorice and dark fruit are so impressive. It’s so exuberant and wild. It just goes on for ever. Spellbinding. Very muscular and powerful. Agile and energetic. Please give this time. Needs eight to ten years. Try from 2029.", score: 98, price: 4000, country: "France", region: "Pomerol, Bordeaux", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/202512.jpg")

Wine.create!(title: "Chateau d'Yquem", year: 2010, varietal: "Dessert", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/x2th26huqkz7wpnlj6no.jpg
", description: "Impressively balanced, with the fruit rich, intense with a golden glow. The acidity is as important as the freshness, giving a delicious lift to the core of dry, concentrated botrytis. Obviously a great wine for long-term aging in a great Sauternes year.", score: 98, price: 550, country: "France", region: "Sauternes, Bordeaux", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/rcnkzvxciu6ejsguhiuy.jpg")

Wine.create!(title: "Achaval-Ferrer Finca Altamira", year: 2015, varietal: "Malbec", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/sfx5jegty3hkjcwzlpex.jpg
", description: "This remarkable wine deserves its place at or close to the summit of the Argentinean fine wine scene. Sourced from a vineyard at 1,100 metres in Paraje Altamira, it’s herbal, textured and spicy with notes of tobacco pouch, Asian spices, dense, plummy fruit, filigree tannins and a long, balanced, tapering finish. 2020-30", score: 93, price: 135, country: "Argentina", region: "Mendoza", img_url:"https://www.wine.com/product/images/w_1024,h_1590,c_fit,q_auto:good,fl_progressive/c7ztyxtj6jhv3lj4q3li.jpg")

Wine.create!(title: "Sine Qua Non 17th Nail in My Cranium", year: 2005, varietal: "Syrah/Shiraz", second_img_url:"https://www.wine.com/product/images/w_768,h_1629,c_fit,q_auto:good,fl_progressive/107309bbs.jpg
", description: "Fantastic spice aromas lead to notes of fresh ground black pepper, beef carpaccio, rich blackberry and roasted coffee, giving this an exotic mix of flavors. Dense, concentrated, structured and tightly focused, striking a balance between the broad array of flavors and the firm tannins. Drink now through 2018. 398 cases made.", score: 98, price: 1200, country: "USA", region: " Sta. Rita Hills, CA", img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/q2tidr6rw9hueeimwd5m.jpg")

Wine.create!(title: "Vineyard 29 Aida Estate", year: 2006, varietal: "Cabernet Sauvignon", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/ihjnelnulycrk5hnozgw.jpg
", description: "The deep purple-black colored 2006 Cabernet Sauvignon Aida Estate Vineyard comes strutting out of the glass like a total rock star, giving up flamboyant notes of warm cassis, blueberry compote and preserved plums with exciting sparks of kirsch, red roses, oolong tea, star anise and cigar box plus a touch of underbrush. Full-bodied, rich, bold and wonderfully decadent in the mouth, it fills the palate with black fruit preserves and red berry layers, supported by a firm, grainy line and finishing very long.", score: 98, price: 295, country: "USA", region: " St. Helena, Napa Valley, CA", img_url:"https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.wilkinsonwinecellar.com%2Fimages%2Fproducts%2Fdetail%2FVineyard29CabernetSauvignonAidaEstateNapaValley2006.jpg&f=1&nofb=1")

Wine.create!(title: "Dom Perignon", year: 2008, varietal: "Sparkling Wine", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/urtiehasqmvh4s3hijrh.jpg
", description: "The best Dom since 2002. A vintage with very restrained, powerful style that has been released non-sequentially after the 2009. This has a lighter stamp of highly curated, autolytic, toasty aromas than many recent releases. Instead, this delivers super fresh and intense aromas of lemons, grapefruit and blood-orange peel. Incredible freshness here. The palate has a very smoothly delivered, berry-pastry thread with light, sweet spices, stone fruit and fine citrus fruit. This really delivers. Drink now or hold.", score: 95, price: 190, country: "France", region: "Champagne", img_url:"https://www.wine.com/product/images/w_1920,h_2088,c_fit,q_auto:good,fl_progressive/cklazsbjr2hlyrbem4px.jpg")

Wine.create!(title: "Louis Latour Romanee-St-Vivant Les Quatre Journaux Grand Cru", year: 2016, varietal: "Pinot Noir", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/xb6fpncjvoffdbmqtaga.jpg
", description: "This is a grand cru that shows its intensity and complexity and greatness from the beginning. Blackberry, licorice and stone aromas. Full body and a center palate that shows ripe fruit and full richness. Then the tannins kick in. Great wine. Drink in 2024.", score: 96, price: 625, country: "France", region: " Vosne-Romanee, Cote de Nuits, Cote d'Or, Burgundy", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/sgvo7h7zvgn65bt8zmst.jpg")

Wine.create!(title: "Marcassin Marcassin Vineyard", year: 2005, varietal: "Pinot Noir", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/bpbhqnco9xfqhjtiexeb.jpg
", description: "Fresh floral and berry aromas are firm, ripe, intense and delicate on the palate, under- rather than overstated, with taut wild berry, mineral, sage and underbrush, finishing with a persistent mix of mineral and berry.", score: 94, price: 350, country: "USA", region: "Sonoma Coast, Sonoma County, CA", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/107306.jpg")

Wine.create!(title: "Vie di Romans Dessimis", year: 2017, varietal: "Pinot Gris/Grigio", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/iw4e1019pxwfp6rnorvo.jpg
", description: "A beautifully colored and intense pinot grigio with sliced cooked apples and peaches and hints of watermelon and almonds. Full body. Very creamy texture and a flavorful finish. Drink or hold.", score: 90, price: 36, country: "Italy", region: "Friuli-Venezia Giulia", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/gw3h397lih902gonx4or.jpg")

Wine.create!(title: "Masseto", year: 2016, varietal: "Merlot", second_img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/zsxgxzltruns63r7inxp.jpg
", description: "This is so solid and powerful with incredible vertical dense that goes down and down on the palate. Compacted and thick with caressing and polished tannins that are powerful yet refined. Super concentration yet agile and energetic. This is a wine that needs time to come together and resolve all of its amazing components. Reminds me of the legendary 2001. Try after 2023.", score: 97, price: 800, country: "Italy", region: "Tuscany", img_url:"https://www.wine.com/product/images/w_1024,h_1468,c_fit,q_auto:good,fl_progressive/rxgaijz2m3qxbhfgfsvr.jpg")

Wine.create!(title: "Castello di Bossi Riserva Berardo", year: 2015, varietal: "Sangiovese", second_img_url:"https://www.wine.com/product/images/w_1440,h_5480,c_fit,q_auto:good,fl_progressive/c6if5anz3bzlzvux90be.jpg", description: "This is racy, taut and intense, with cherry, black currant and blueberry flavors fused to a severe structure. Shows mineral and black pepper details as this rides out the refreshing finish. Give this some time. Best from 2022 through 2045.", score: 93, price: 35, country: "Italy", region: "Chianti Classico", img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/yhltxlr0y7buprmnjjug.jpg")

Wine.create!(title: "Bodegas Vega Sicilia Unico Tinto", year: 2006, varietal: "Tempranillo", second_img_url:"https://www.wine.com/product/images/w_1440,h_4379,c_fit,q_auto:good,fl_progressive/lyfq7xax03irs92ngchw.jpg
", description: "Silky and dense, this red delivers focused flavors of currant, licorice, tobacco and mineral, supported by well-integrated tannins and fresh acidity. Not showy, but has depth. Lithe and energetic. Drink now through 2021. 7,800 cases made.", score: 94, price: 450, country: "Spain", region: "Ribera del Duero", img_url:"https://www.wine.com/product/images/w_1024,h_1252,c_fit,q_auto:good,fl_progressive/hfqe7bahrj8wsuuyaiuk.jpg")













#Reviews
Review.create!(content:"The 2014 Screaming Eagle is an 880-case blend of 79% Cabernet Sauvignon, 16% Merlot and the rest Cabernet Franc. The telltale sign of this iconic wine is its extraordinary purity of crème de cassis fruit, which is displayed abundantly in the 2014. It doesn’t quite have the structure and mass of the 2013, but this sexy, up-front, opaque ruby/purple-colored wine is seamlessly constructed, full-bodied, and has a long finish with silky tannins. This seems to float across that palate with that great fruit purity that is a characteristic of Screaming Eagle.", wine_id:1, user_id:1)
Review.create!(content:"The 2017 Zinfandel Papera Ranch comes from vines planted in 1934. It contains 4% Carignane and was aged in 25% new French oak. It's medium to deep ruby-purple in the glass with aromas of apricot and nectarine, boysenberry, black cherry and raspberry jam, red cherries and fried sage with hints of charcuterie, spices and flowers. The palate is medium-bodied and silky, flooding the mouth with spicy fruits in a chewy frame and lifted by juicy freshness on the long finish. This merits another few years in bottle.", wine_id:2, user_id:1)
Review.create!(content:"A brilliant offering and a candidate for wine of the vintage, this is classic Lafite that reminded me somewhat of the 1976, although the vintage conditions were completely different. This is a medium-weight, quintessentially elegant style of Lafite with notes of lead pencil shavings/graphite along with black currants, plums, and crushed rocks/mineral. Wonderfully pure, dense, with a deep ruby/purple color and loads of fruit, definition, and a long finish, this is a brilliant, elegant Lafite Rothschild that builds incrementally in the mouth and has more power and density than it initially seems.", wine_id:3, user_id:2)
Review.create!(content:"Nobilo wines are proudly hailed as some of New Zealand's most respected pioneering wine brands. A Croat immigrant, Nikola Nobilo, whose family history and winemaking background stretches back over 300 years to the Adriatic island of Korcula off the Dalmatian coast, led the way. The history of the company in New Zealand goes back to the early 1940's when this Croatian family, landed in New Zealand. They settled in Huapai, West Auckland situated in the North Island of New Zealand, and started planting vines in 1943. With over 300 years of European wine history, this family effectively persuaded and guided the NZ wine industry away from hybrid grape varieties and fortified wines, to a higher level of quality wine, now recognised and appraised by all markets. ", wine_id:4, user_id:1)
Review.create!(content:"A much more elegant nose reflects notes of acacia blossom white peach, essence of spiced pear and hints of mandarin and oak. There is fine richness to the generously proportioned but well-focused medium-bodied flavors that terminate in a driving, linear and bone dry finish that offers excellent depth and persistence. This is a fine Puligny villages. ", wine_id:5, user_id:2)
Review.create!(content:"One of the top sparkling deals in the world, the non-vintage Nino Franco Rustico Valdobbiadene Prosecco Superiore exhibits a beautifully refined mousse and fresh, tart apple flavors. The wine's crisp finish pairs it perfectly with delicate appetizers. (Tasted: February 16, 2016, Treasure Island, CA) ", wine_id:6, user_id:1)
Review.create!(content:"Opaque purple-black colored, the 2016 Petrus slips effortlessly out of the glass with sanguine, seductive notes of kirsch, warm black plums, blueberry compote, red roses, Ceylon tea, violets, dark chocolate-covered cherries, licorice and cinnamon stick with wafts of iron ore, pencil lead, unsmoked cigars and crushed rocks. Full-bodied, profound and absolutely edifying on the palate, the densely packed, beautifully perfumed red and blue fruit layers possess a charge like defibrillators stimulating your heart to be faster, each delivering achingly subtle floral and spice sparks, perfectly framed by very firm, very grainy tannins and bold freshness, finishing with incredible length and taking you to depths that extend to a provocative ferrous undercurrent. Stunning. ", wine_id:7, user_id:2)
Review.create!(content:"The purity of Botrytis in this wine is so impressive with dried fruits such apple and mango. And then spicy character. Full body and very sweet but it is incredibly fresh and lively. Such class and elegance. Perfectly manicured wine. Everything in the right place. This shows a delicacy and intensity that are spellbinding.", wine_id:8, user_id:1)
Review.create!(content:"This remarkable wine deserves its place at or close to the summit of the Argentinean fine wine scene. Sourced from a vineyard at 1,100 metres in Paraje Altamira, it’s herbal, textured and spicy with notes of tobacco pouch, Asian spices, dense, plummy fruit, filigree tannins and a long, balanced, tapering finish. ", wine_id:9, user_id:1)
Review.create!(content:"Black as a moonless night, the 2005 17th Nail reveals a stunning nose of spring flowers intermixed with creme de cassis, blackberries, charcoal, graphite, and hints of lard and barbecue spices. Dense, with an endless (and I mean endless) finish, remarkable purity, and layer upon layer of flavor, but no sense of heaviness or flabbiness, this prodigious Syrah should evolve for 15 or more years.", wine_id:10, user_id:1)
Review.create!(content:"The Cabernet Sauvignon from the Aida Vineyard is becoming one of the most exceptional northern Napa Valley Cabernets, with a production ranging between 600-700 cases. The dense ruby/purple-tinged 2006 Cabernet Sauvignon Aida Vineyard reveals aromas of melted chocolate, scorched earth, pepper, and creme de cassis. Fashioned from 83% Cabernet Sauvignon and the rest Merlot, Petit Verdot, and a touch of Cabernet Franc, it exhibits a superb texture along with those notions of charcoal and burning embers that come from this rock-laden soil. This full-bodied 2006 is more masculine and muscular than the 2005, without that wine’s complexity (of course, it has been in bottle for less time). While it is a successful wine for the vintage, buyers will need to be patient as it requires 2-3 years of bottle age; it should drink well for 20 years.", wine_id:11, user_id:1)
Review.create!(content:"The 2008 Dom Pérignon is the first time the estate has released a wine out of order (the 2009 was released before the 2008) but the estate loved the wine so much they felt it warranted additional aging. This is a rich, powerful wine that still shows incredible purity and elegance, with a stacked, concentrated feel on the palate. It’s rare to find such a mix of ripe, pure, concentrated fruit paired with this level of purity, focus, and precision. This is a legendary Dom that surpasses all the great vintages of Dom I have experience with, including the 1990, 1996, and 2002.", wine_id:12, user_id:1)
Review.create!(content:"Good though the Chambertin is, the Romanée-St-Vivant is the king of the cellar in 2016, soaring from the glass with a pure and creamy bouquet of black cherry, currant, candied peel and subtle spice. Expansive, full-bodied and concentrated, framed by fine but firm tannins, this is really a very serious rendition of what is arguably the finest plot of this great grand cru vineyard.", wine_id:13, user_id:1)
Review.create!(content:"Utterly profound, the 2005 Pinot Noir Marcassin Estate has a deep plum/ruby/purple-tinged color and a sweet nose of black raspberries, roasted meats, forest aromas, soy, and fresh mushrooms. Layered and multi-dimensional, with sweet but noticeable tannin, and broad, intense flavors, this is a stunning wine that should drink nicely for a decade or more.", wine_id:14, user_id:1)
Review.create!(content:"This is a rich and flamboyant pinot grigio, its juicy flavors of pale strawberry and peach overshadowed by notes of toasted nuts and spice from nine months in barriques. The warm, weighty finish is refreshed by balancing mandarin-like acidity. ", wine_id:15, user_id:1)
Review.create!(content:"The 2016 Masseto is sensational and unquestionably one of the greatest expressions of Merlot in the world. As always, it's 100% Merlot from a single vineyard that has a complex, diverse set of soils and expositions, causing harvest at times to be spread over as much as three weeks. Aged two years in oak, its deep purple color is followed by a powerful bouquet of black cherries, cassis, spicy oak, damp earth, green tobacco, and spring flowers. It's full-bodied, concentrated and masculine on the palate, with serious minerality, yet it stays flawlessly balanced with magical purity of fruit. With no shortage of concentration and structure, this primordial powerhouse of a Merlot needs 4-6 years of bottle age yet should evolve for decades. Merlot, or wine for that matter, doesn’t get any better!", wine_id:16, user_id:1)
Review.create!(content:"The 2015 Chianti Classico Riserva Berardo exhibits a soft and delicate personality that is slightly atypical for this warm and sunny vintage and for the Castelnuovo Berardenga subzone that is known for more robust interpretations. Instead, this wine exhibits fine silkiness with aromas of wild berry, spice, crushed stone and even a touch of grilled herb or green olive. There is a drying note on the bouquet that recalls the crushed rocks and limestone clay soils of Chianti Classico. Some 60,000 bottles were made. You get great value here.", wine_id:17, user_id:1)
Review.create!(content:"The elevage is complex, building from smaller barrels to larger barrels over a period of six years, finishing in larger vats. Then four years in bottle. This 2006 has good ripeness and deep fruit-presence on the nose with rich red and dark plums, subtly earthy spice, cedar and fresh tobacco. There’s terrific concentration on the palate and very ripe dark-plum, blueberry and cherry flavors. The tannins are fresh, very long and carry flavors deep. Natural freshness and effortless power, too — a hallmark of Unico! Very open-knit and approachable now, this will age for two decades easily, and then some more.", wine_id:18, user_id:1)
Review.create!(content:"Bottled in mid-August, this is already taking on the most amazing slow creep of well-defined, crisp violet, cassis, tight black fruits and fig notes; floral and fresh yet complex and ripe. It's balanced by the most gorgeous burst of mint and slate, all stretching out slowly, delicately, gently. It's more architectural than the monumental 2015, but no less impressive, beginning to really settle and take its time to gather its forces, to layer itself up. A pure, precise style, it holds your attention for many many minutes after the wine has gone, both aromatically and intellectually. The overall impression is simply of pleasure. 50% new oak.", wine_id:7, user_id:1)
Review.create!(content:"Beautifully crafted, young and energetic, with a vibrant core of rich blackberry, gravelly earth and smoky, toasty oak. Lively acidity and firm tannins provide a backbone, promising a long life ahead. Best from 2020 through 2034.", wine_id:1, user_id:2)
Review.create!(content:"It displays, as Lafite always does, more of a laid back elegance than Latour, and the difference between the two once again highlights the huge differences in terroir between north and south Pauillac, with the deep gravels here giving finesse, composure, almost nonchalance. It tames with a whisper, bringing you to submission by gently, purposefully and ever so slowly layering one thing on top of another. It has gorgeously pure and precise fruit on the nose, while the palate displays a multitude of flavours, from charcoal to cassis to crushed stone, and yet no one thing dominates. There are a ton of tannins, but they are individually fine, and it's only in retrospect that you realise how many of them there are. The tone of Lafite is speaking over the vintage, and it's going to run and run.", wine_id:3, user_id:1)


o1 = Order.create!(user:u1, status:"complete", shipped_to:"123 poop", total:5)
o1.wines << w1
