# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)




u1 = User.create(name:"nick", password:"password", dateofbirth:Date.parse('1991-08-21'), email:"email@email.com", avatar_url:"https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fcruiseweb.com%2Fblog%2Fwp-content%2Fuploads%2F2014%2F01%2Fwinelovers.jpg&f=1&nofb=1", city:"city", state:"state", address:"address", zipcode:12345)
u2 = User.create(name:"rick", password:"password", dateofbirth:Date.parse('2001-08-21'), email:"email@email.com", avatar_url:"https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.todayifoundout.com%2Fwp-content%2Fuploads%2F2018%2F05%2Fwine-snob-640x445.png&f=1&nofb=1", city:"city", state:"state", address:"address", zipcode:12345)

o1 = Order.create(status: "Delivered", user_id:1, order_date: "date", shipped_to:"address")
o2 = Order.create(status: "Not Delivered", user_id:2, order_date:"date", shipped_to:"none")

r1 = Review.create(content:"content1", wine_id:1, rating:4, user_id:2)
r2 = Review.create(content:"content2", wine_id:2, rating:5, user_id:1)

#wines

Wine.create!(title: "Screaming Eagle", year: 2014, varietal: "Cabernet Sauvignon", description: "Extremely perfumed with blackberries, currants and flower. Rose petals, too. Seductive. Medium to full body. It grows on the palate with an extremely long finish that goes on for minutes. The tannins are ultra-fine and polished. Purity and essence to this. Feminine yet wild and unpredictable. Available in March. Better in 2021.", score: 95, price: 3000, country: "USA", region: "Napa Valley, CA", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/165265.jpg")
Wine.create!(title: "Carlisle Papera Ranch", year: 2017, varietal: "Zinfandel", description: "The 2017 Zinfandel Papera Ranch comes from a site close to the Mancini Ranch and vines planted in 1934. Notes of plums, blueberries, violets, and earthy, herbal notes all flow to a full-bodied, incredibly deep, layered and concentrated 2017 that certainly makes the most of the vintage. With ripe tannins, remarkable purity of fruit, no hard edges, and flawless balance, it’s another gem in the vintage.", score: 94, price: 52, country: "USA", region: "Russian River, CA", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/jrfynqsxbtozhgyxcf9f.jpg")
Wine.create!(title: "Chateau Lafite Rothschild", year: 2009, varietal: "Bordeaux", description: "This is stunning for its ability to take massively endowed fig, currant paste and crushed plum fruit flavors and harness them with ultrasuave freshly roasted espresso, black tea and ganache notes. A seductive style, long and velvety, with the dense core of black fruit and smoldering iron just waiting and waiting. Best from 2020 through 2040.", score: 98, price: 1250, country: "France", region: "Pauillac, Bordeaux", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/111778.jpg")
Wine.create!(title: "Nobilo", year: 2018, varietal: "Sauvignon Blanc", description: "Fresh, crisp and clean with zesty flavors of ripe tropical fruits, especially passionfruit and pineapple with subtle hints of green herbs. The wine is intensely flavored with balanced mouthwatering acidity and a generous finish.", score: 89, price: 12, country: "New Zealand ", region: "Marlborough", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/dfhr3cjnfn6u7elqk75j.jpg")
Wine.create!(title: "Olivier Leflaive", year: 2017, varietal: "Chardonnay", description: "Fermented and aged in wood, this is a rich wine. Its spice, ripe pineapple and mango flavors and dense texture show intense freshness as well as layers of toast, a complex texture and a short aging potential. Drink from 2021.", score: 82, price: 90, country: "France", region: "Puligny-Montrachet, Cote de Beaune, Cote d'Or, Burgundy, France", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/wo6adueiwjczv2wu3qf3.jpg")
Wine.create!(title: "Nino Franco Rustico Prosecco Superiore", year: 2016, varietal: "Sparkling Wine", description: "Aromas of white spring flower, Bartlett pear and citrus waft out of the glass. The racy, refreshing palate is full of energy, offering crisp yellow-apple, lemon drop and orange zest flavors balanced by vibrant acidity. A perlage of small, refined and continuous bubbles provides the silky backdrop.", score: 94, price: 20, country: "Italy", region: "Valdobbiadene, Prosecco", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/vffikxhgjrsuciyefctp.jpg")
Wine.create!(title: "Chateau Petrus", year: 2016, varietal: "Bordeaux", description: "This is very fleshy and deep with so much texture and richness. It’s full-bodied yet fresh. The tobacco, white truffle, licorice and dark fruit are so impressive. It’s so exuberant and wild. It just goes on for ever. Spellbinding. Very muscular and powerful. Agile and energetic. Please give this time. Needs eight to ten years. Try from 2029.", score: 98, price: 4000, country: "France", region: "Pomerol, Bordeaux", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/202512.jpg")
Wine.create!(title: "Chateau d'Yquem", year: 2010, varietal: "Dessert", description: "Impressively balanced, with the fruit rich, intense with a golden glow. The acidity is as important as the freshness, giving a delicious lift to the core of dry, concentrated botrytis. Obviously a great wine for long-term aging in a great Sauternes year.", score: 98, price: 550, country: "France", region: "Sauternes, Bordeaux", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/rcnkzvxciu6ejsguhiuy.jpg")
Wine.create!(title: "Achaval-Ferrer Finca Altamira", year: 2015, varietal: "Malbec", description: "This remarkable wine deserves its place at or close to the summit of the Argentinean fine wine scene. Sourced from a vineyard at 1,100 metres in Paraje Altamira, it’s herbal, textured and spicy with notes of tobacco pouch, Asian spices, dense, plummy fruit, filigree tannins and a long, balanced, tapering finish. 2020-30", score: 93, price: 135, country: "Argentina", region: "Mendoza", img_url:"https://www.wine.com/product/images/w_1024,h_1590,c_fit,q_auto:good,fl_progressive/c7ztyxtj6jhv3lj4q3li.jpg")
Wine.create!(title: "Sine Qua Non 17th Nail in My Cranium", year: 2005, varietal: "Syrah/Shiraz", description: "Fantastic spice aromas lead to notes of fresh ground black pepper, beef carpaccio, rich blackberry and roasted coffee, giving this an exotic mix of flavors. Dense, concentrated, structured and tightly focused, striking a balance between the broad array of flavors and the firm tannins. Drink now through 2018. 398 cases made.", score: 98, price: 1200, country: "USA", region: " Sta. Rita Hills, CA", img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/q2tidr6rw9hueeimwd5m.jpg")
Wine.create!(title: "Vineyard 29 Aida Estate", year: 2006, varietal: "Cabernet Sauvignon", description: "The deep purple-black colored 2006 Cabernet Sauvignon Aida Estate Vineyard comes strutting out of the glass like a total rock star, giving up flamboyant notes of warm cassis, blueberry compote and preserved plums with exciting sparks of kirsch, red roses, oolong tea, star anise and cigar box plus a touch of underbrush. Full-bodied, rich, bold and wonderfully decadent in the mouth, it fills the palate with black fruit preserves and red berry layers, supported by a firm, grainy line and finishing very long.", score: 98, price: 295, country: "USA", region: " St. Helena, Napa Valley, CA", img_url:"https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.wilkinsonwinecellar.com%2Fimages%2Fproducts%2Fdetail%2FVineyard29CabernetSauvignonAidaEstateNapaValley2006.jpg&f=1&nofb=1")
Wine.create!(title: "Dom Perignon", year: 2008, varietal: "Sparkling Wine", description: "The best Dom since 2002. A vintage with very restrained, powerful style that has been released non-sequentially after the 2009. This has a lighter stamp of highly curated, autolytic, toasty aromas than many recent releases. Instead, this delivers super fresh and intense aromas of lemons, grapefruit and blood-orange peel. Incredible freshness here. The palate has a very smoothly delivered, berry-pastry thread with light, sweet spices, stone fruit and fine citrus fruit. This really delivers. Drink now or hold.", score: 95, price: 190, country: "France", region: "Champagne", img_url:"https://www.wine.com/product/images/w_1920,h_2088,c_fit,q_auto:good,fl_progressive/cklazsbjr2hlyrbem4px.jpg")
Wine.create!(title: "Louis Latour Romanee-St-Vivant Les Quatre Journaux Grand Cru", year: 2016, varietal: "Pinot Noir", description: "This is a grand cru that shows its intensity and complexity and greatness from the beginning. Blackberry, licorice and stone aromas. Full body and a center palate that shows ripe fruit and full richness. Then the tannins kick in. Great wine. Drink in 2024.", score: 96, price: 625, country: "France", region: " Vosne-Romanee, Cote de Nuits, Cote d'Or, Burgundy", img_url:"https://www.wine.com/product/images/w_768,c_fit,q_auto:good,fl_progressive/sgvo7h7zvgn65bt8zmst.jpg")
Wine.create!(title: "Marcassin Marcassin Vineyard", year: 2005, varietal: "Pinot Noir", description: "Fresh floral and berry aromas are firm, ripe, intense and delicate on the palate, under- rather than overstated, with taut wild berry, mineral, sage and underbrush, finishing with a persistent mix of mineral and berry.", score: 94, price: 350, country: "USA", region: "Sonoma Coast, Sonoma County, CA", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/107306.jpg")
Wine.create!(title: "Vie di Romans Dessimis", year: 2017, varietal: "Pinot Gris/Grigio", description: "A beautifully colored and intense pinot grigio with sliced cooked apples and peaches and hints of watermelon and almonds. Full body. Very creamy texture and a flavorful finish. Drink or hold.", score: 90, price: 36, country: "Italy", region: "Friuli-Venezia Giulia", img_url:"https://www.wine.com/product/images/w_480,c_fit,q_auto:good,fl_progressive/gw3h397lih902gonx4or.jpg")
Wine.create!(title: "Masseto", year: 2016, varietal: "Merlot", description: "This is so solid and powerful with incredible vertical dense that goes down and down on the palate. Compacted and thick with caressing and polished tannins that are powerful yet refined. Super concentration yet agile and energetic. This is a wine that needs time to come together and resolve all of its amazing components. Reminds me of the legendary 2001. Try after 2023.", score: 97, price: 800, country: "Italy", region: "Tuscany", img_url:"https://www.wine.com/product/images/w_1024,h_1468,c_fit,q_auto:good,fl_progressive/rxgaijz2m3qxbhfgfsvr.jpg")
Wine.create!(title: "Castello di Bossi Riserva Berardo", year: 2015, varietal: "Sangiovese", description: "This is racy, taut and intense, with cherry, black currant and blueberry flavors fused to a severe structure. Shows mineral and black pepper details as this rides out the refreshing finish. Give this some time. Best from 2022 through 2045.", score: 93, price: 35, country: "Italy", region: "Chianti Classico", img_url:"https://www.wine.com/product/images/w_480,h_600,c_fit,q_auto:good,fl_progressive/yhltxlr0y7buprmnjjug.jpg")
Wine.create!(title: "Bodegas Vega Sicilia Unico Tinto", year: 2006, varietal: "Tempranillo", description: "Silky and dense, this red delivers focused flavors of currant, licorice, tobacco and mineral, supported by well-integrated tannins and fresh acidity. Not showy, but has depth. Lithe and energetic. Drink now through 2021. 7,800 cases made.", score: 94, price: 450, country: "Spain", region: "Ribera del Duero", img_url:"https://www.wine.com/product/images/w_1024,h_1252,c_fit,q_auto:good,fl_progressive/hfqe7bahrj8wsuuyaiuk.jpg")

